Traceback (most recent call last):
  File "/usr/local/bin/myth", line 4, in <module>
    __import__('pkg_resources').run_script('mythril==0.18.6', 'myth')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.6-py3.6.egg/EGG-INFO/scripts/myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.6-py3.6.egg/mythril/interfaces/cli.py", line 159, in main
    address, _ = mythril.load_from_solidity(args.solidity_file)  # list of files
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.6-py3.6.egg/mythril/mythril.py", line 305, in load_from_solidity
    contract = SolidityContract(file, contract_name, solc_args=self.solc_args)
  File "/usr/local/lib/python3.6/dist-packages/mythril-0.18.6-py3.6.egg/mythril/ether/soliditycontract.py", line 89, in __init__
    lineno = self.solidity_files[idx].data[0:offset].count('\n') + 1
IndexError: list index out of range